### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by littlepea** [yangxu/google_flight_api#1]
Hi,

This is a great implementation for the QPX Express API!
Would be great to have it installable by pip!

P.S. Do you live in China? Looking for a job in Python and travel industry? ;)

**Comment by yangxu** [comment]
Good point. I may try this after Christmas.

P.S. I'm currently living in Massachusetts. Love writing code. :)

**Comment by yangxu** [comment]
Done.
pip install google_flight_api

**Comment by littlepea** [comment]
Awesome, thanks!
